# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b0c0b136c4ae54c16a71e57aebafdee6b37ccd54cb1d610944ebb0d0b83ae4dee50da9dff63432f1abe25198d5a58ddf5e7f59fb45325d382cb2952ac175863

test:
  secret_key_base: 635602ad4a24d93201bc8726b50b618aab07a205c59875fb56ca20c22d8dc2a5d6bd9b70317fe25e21edfc438441d6e0040f87d5a5c49384d52d910ef65dba4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
